### ISSUE TITLE
In description 

### ISSUE THREAD

**Issue by playday3008** [BytewaveMLP/Randibooru.js#4]
![image](https://user-images.githubusercontent.com/18056374/85395168-01c63700-b550-11ea-9790-aa16c1e9af47.png)

**Comment by BytewaveMLP** [comment]
The bot is either missing the Embed Links permission, or you have link previews disabled under "text and images" in your client settings.

**Comment by playday3008** [comment]
![image](https://user-images.githubusercontent.com/18056374/85436098-c85ded80-b588-11ea-81c8-3ca50fa45207.png)
![image](https://user-images.githubusercontent.com/18056374/85436140-d7dd3680-b588-11ea-8d2e-8836b35bf155.png)
All enabled

**Comment by BytewaveMLP** [comment]
The bot produces embeds correctly for me:

![](https://i.imgur.com/Kl2MDPk.png)

Are you sure there are no channel overrides which prevent the bot from embedding links?

**Comment by playday3008** [comment]
I know what the problem is, another bot overwrite the Randibooru role settings, thx
